# Copyright (C) 2017 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/NUBIA/NX404H/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/NUBIA/NX404H/proprietary/bin/fmconfig:system/bin/fmconfig \
    vendor/NUBIA/NX404H/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/NUBIA/NX404H/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/NUBIA/NX404H/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/NUBIA/NX404H/proprietary/bin/tp_node.sh:system/bin/tp_node.sh \
    vendor/NUBIA/NX404H/proprietary/bin/uiautomator:system/bin/uiautomator \
    vendor/NUBIA/NX404H/proprietary/bin/wcnss_service:system/bin/wcnss_service \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/NUBIA/NX404H/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/zte/x9180/proprietary/etc/firmware/Signedrompatch_v20.bin:system/etc/firmware/Signedrompatch_v20.bin \
    vendor/zte/x9180/proprietary/etc/firmware/Signedrompatch_v21.bin:system/etc/firmware/Signedrompatch_v21.bin \
    vendor/zte/x9180/proprietary/etc/firmware/Signedrompatch_v24.bin:system/etc/firmware/Signedrompatch_v24.bin \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/zte/x9180/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/zte/x9180/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/zte/x9180/proprietary/lib/hw/camera.msm8226.so:system/lib/hw/camera.msm8226.so \
    vendor/zte/x9180/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/zte/x9180/proprietary/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so \
    vendor/zte/x9180/proprietary/lib/libDocPretty.so:system/lib/libDocPretty.so \
    vendor/zte/x9180/proprietary/lib/libDocVfbEngineLib.so:system/lib/libDocVfbEngineLib.so \
    vendor/zte/x9180/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/zte/x9180/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/zte/x9180/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/zte/x9180/proprietary/lib/libmorpho_image_converter.so:system/lib/libmorpho_image_converter.so \
    vendor/zte/x9180/proprietary/lib/libmorpho_jpeg_io.so:system/lib/libmorpho_jpeg_io.so \
    vendor/zte/x9180/proprietary/lib/libmorpho_memory_allocator.so:system/lib/libmorpho_memory_allocator.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/zte/x9180/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/zte/x9180/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/zte/x9180/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/zte/x9180/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/zte/x9180/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_nightmode_1.so:system/vendor/lib/libchromatix_imx135_nightmode_1.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_nightmode.so:system/vendor/lib/libchromatix_imx135_nightmode.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_common.so:system/vendor/lib/libchromatix_ov5648_common.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_default_video.so:system/vendor/lib/libchromatix_ov5648_default_video.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_preview.so:system/vendor/lib/libchromatix_ov5648_preview.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_snapshot.so:system/vendor/lib/libchromatix_ov5648_snapshot.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_video_hd.so:system/vendor/lib/libchromatix_ov5648_video_hd.so \
    vendor/zte/x9180/proprietary/vendor/lib/libchromatix_ov5648_zsl.so:system/vendor/lib/libchromatix_ov5648_zsl.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_ov5648.so:system/vendor/lib/libmmcamera_ov5648.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/zte/x9180/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/NUBIA/NX404H/proprietary/lib/libBlurEffect.so:system/lib/libBlurEffect.so \
    vendor/NUBIA/NX404H/proprietary/lib/libbuffer_manager.so:system/lib/libbuffer_manager.so \
    vendor/NUBIA/NX404H/proprietary/lib/libnubia_effect.so:system/lib/libnubia_effect.so \
    vendor/NUBIA/NX404H/proprietary/lib/libnubiajpeg.so:system/lib/libnubiajpeg.so \
    vendor/NUBIA/NX404H/proprietary/lib/libnubia_runtime.so:system/lib/libnubia_runtime.so \


ifeq ($(QCPATH),)
PRODUCT_COPY_FILES += \
    vendor/NUBIA/NX404H/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/NUBIA/NX404H/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/NUBIA/NX404H/proprietary/bin/dun-server:system/bin/dun-server \
    vendor/NUBIA/NX404H/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/NUBIA/NX404H/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/NUBIA/NX404H/proprietary/bin/loc_launcher:system/bin/loc_launcher \
    vendor/NUBIA/NX404H/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/NUBIA/NX404H/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/NUBIA/NX404H/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/NUBIA/NX404H/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/NUBIA/NX404H/proprietary/bin/radish:system/bin/radish \
    vendor/NUBIA/NX404H/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/NUBIA/NX404H/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/NUBIA/NX404H/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/NUBIA/NX404H/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/NUBIA/NX404H/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/NUBIA/NX404H/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/NUBIA/NX404H/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/NUBIA/NX404H/proprietary/lib/hw/sensors.oem.so:system/lib/hw/sensors.oem.so \
    vendor/NUBIA/NX404H/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/NUBIA/NX404H/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/NUBIA/NX404H/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/NUBIA/NX404H/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/hw/sensors.msm8228.so:system/vendor/lib/hw/sensors.msm8228.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/NUBIA/NX404H/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    libmdmdetect \
    libdiag \
    libdsutils \
    libidl \
    libqmi_client_qmux \
    libqmiservices \
    libqmi \
    libtime_genoff \
    libTimeService \
    TimeService \
    qcnvitems \
    qcrilhook
endif
