# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/NUBIA/X9180/proprietary/vendor/bin/fm_qsoc_patches:system/vendor/bin/fm_qsoc_patches \
    vendor/NUBIA/X9180/proprietary/vendor/bin/fmconfig:system/vendor/bin/fmconfig \
    vendor/NUBIA/X9180/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/NUBIA/X9180/proprietary/vendor/bin/uiautomator:system/vendor/bin/uiautomator \
    vendor/NUBIA/X9180/proprietary/vendor/bin/gpsone_daemon:system/vendor/bin/gpsone_daemon \
    vendor/NUBIA/X9180/proprietary/bin/tp_node.sh:system/bin/tp_node.sh \
    vendor/NUBIA/X9180/proprietary/vendor/bin/garden_app:system/vendor/bin/garden_app \
    vendor/NUBIA/X9180/proprietary/lib/libBlurEffect.so:system/lib/libBlurEffect.so \
    vendor/NUBIA/X9180/proprietary/lib/libnubia_runtime.so:system/lib/libnubia_runtime.so \
    vendor/NUBIA/X9180/proprietary/vendor/bin/loc_launcher:system/vendor/bin/loc_launcher \
    vendor/NUBIA/X9180/proprietary/vendor/bin/location-mq:system/vendor/bin/location-mq \
    vendor/NUBIA/X9180/proprietary/vendor/bin/lowi-server:system/vendor/bin/lowi-server \
    vendor/NUBIA/X9180/proprietary/vendor/bin/quipc_igsn:system/vendor/bin/quipc_igsn \
    vendor/NUBIA/X9180/proprietary/vendor/bin/quipc_main:system/vendor/bin/quipc_main \
    vendor/NUBIA/X9180/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/NUBIA/X9180/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/NUBIA/X9180/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/NUBIA/X9180/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/NUBIA/X9180/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/NUBIA/X9180/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/hw/activity_recognition.msm8226.so:system/vendor/lib/hw/activity_recognition.msm8226.so \
    vendor/NUBIA/X9180/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/NUBIA/X9180/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/NUBIA/X9180/proprietary/etc/firmware/cyttsp4_fw.bin:system/etc/firmware/cyttsp4_fw.bin \
    vendor/NUBIA/X9180/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/NUBIA/X9180/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/NUBIA/X9180/proprietary/lib/hw/camera.vendor.msm8226.so:system/lib/hw/camera.vendor.msm8226.so \
    vendor/NUBIA/X9180/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/NUBIA/X9180/proprietary/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so \
    vendor/NUBIA/X9180/proprietary/lib/libDocPretty.so:system/lib/libDocPretty.so \
    vendor/NUBIA/X9180/proprietary/lib/libDocVfbEngineLib.so:system/lib/libDocVfbEngineLib.so \
    vendor/NUBIA/X9180/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/NUBIA/X9180/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/NUBIA/X9180/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/NUBIA/X9180/proprietary/lib/libmorpho_image_converter.so:system/lib/libmorpho_image_converter.so \
    vendor/NUBIA/X9180/proprietary/lib/libmorpho_jpeg_io.so:system/lib/libmorpho_jpeg_io.so \
    vendor/NUBIA/X9180/proprietary/lib/libmorpho_memory_allocator.so:system/lib/libmorpho_memory_allocator.so \
    vendor/NUBIA/X9180/proprietary/lib/libcurl_camera.so:system/lib/libcurl_camera.so \
    vendor/NUBIA/X9180/proprietary/lib/libFNVfbEngineLib.so:system/lib/libFNVfbEngineLib.so \
    vendor/NUBIA/X9180/proprietary/lib/libFNVfbEngineHAL.so:system/lib/libFNVfbEngineHAL.so \
    vendor/NUBIA/X9180/proprietary/lib/libImageAlogrithm.so:system/lib/libImageAlogrithm.so \
    vendor/NUBIA/X9180/proprietary/lib/libSFB.so:system/lib/libSFB.so \
    vendor/NUBIA/X9180/proprietary/lib/libnubia_effect.so:system/lib/libnubia_effect.so \
    vendor/NUBIA/X9180/proprietary/lib/libnubiajpeg.so:system/lib/libnubiajpeg.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_nightmode_1.so:system/vendor/lib/libchromatix_imx135_nightmode_1.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_nightmode.so:system/vendor/lib/libchromatix_imx135_nightmode.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_common.so:system/vendor/lib/libchromatix_ov5648_common.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_default_video.so:system/vendor/lib/libchromatix_ov5648_default_video.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_preview.so:system/vendor/lib/libchromatix_ov5648_preview.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_snapshot.so:system/vendor/lib/libchromatix_ov5648_snapshot.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_video_hd.so:system/vendor/lib/libchromatix_ov5648_video_hd.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libchromatix_ov5648_zsl.so:system/vendor/lib/libchromatix_ov5648_zsl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_ov5648.so:system/vendor/lib/libmmcamera_ov5648.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/NUBIA/X9180/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/NUBIA/X9180/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libWVphoneAPI.so:system/vendor/lib/libWVphoneAPI.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    vendor/NUBIA/X9180/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/NUBIA/X9180/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
    vendor/NUBIA/X9180/proprietary/vendor/bin/btnvtool:system/vendor/bin/btnvtool \
    vendor/NUBIA/X9180/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/NUBIA/X9180/proprietary/vendor/bin/dun-server:system/vendor/bin/dun-server \
    vendor/NUBIA/X9180/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/NUBIA/X9180/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/NUBIA/X9180/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/NUBIA/X9180/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/NUBIA/X9180/proprietary/vendor/bin/rfs_access:system/vendor/bin/rfs_access \
    vendor/NUBIA/X9180/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/NUBIA/X9180/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/NUBIA/X9180/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
    vendor/NUBIA/X9180/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/NUBIA/X9180/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/NUBIA/X9180/proprietary/lib/hw/sensors.oem.so:system/lib/hw/sensors.oem.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so \
    vendor/NUBIA/X9180/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsrcscmservice.so:system/vendor/lib/lib-imsrcscmservice.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsrcscm.so:system/vendor/lib/lib-imsrcscm.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsrcscmclient.so:system/vendor/lib/lib-imsrcscmclient.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmgesture-bus2.so:system/vendor/lib/libmmgesture-bus2.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libmsapm_jni.so:system/vendor/lib/libmsapm_jni.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libpfecommon.so:system/vendor/lib/libpfecommon.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libprofiler_msmadc.so:system/vendor/lib/libprofiler_msmadc.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libscve_stub.so:system/vendor/lib/libscve_stub.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/lib-sec-disp.so:system/vendor/lib/lib-sec-disp.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libstlport.so:system/vendor/lib/libstlport.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
    vendor/NUBIA/X9180/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so 
